services:
  frontend:
    image: taper-frontend:latest
    build:
      context: .
      args:
        NODE_ENV: ${APP_ENV:-local}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${APP_ENV:-local}
    env_file:
      - .env.example
      - path: .env
        required: false
    volumes:
      - "./taper-frontend:/app"
      - "/srv/taper/node_modules"
      - "/srv/taper/.nuxt"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: unless-stopped
